export interface ThemeColors {
  background: string;
  surface: string;
  surfaceElevated: string;
  primary: string;
  primaryLight: string;
  secondary: string;
  accent: string;
  text: string;
  textSecondary: string;
  textMuted: string;
  border: string;
  success: string;
  warning: string;
  error: string;
  info: string;
  operator: string;
  operatorBg: string;
  number: string;
  numberBg: string;
  function: string;
  functionBg: string;
  equals: string;
  equalsBg: string;
  displayText: string;
  historyText: string;
  keypadBg: string;
  cardBg: string;
  gradientStart: string;
  gradientEnd: string;
  overlay: string;
  shadow: string;
}

export const lightColors: ThemeColors = {
  background: '#F2F2F7',
  surface: '#FFFFFF',
  surfaceElevated: '#FFFFFF',
  primary: '#007AFF',
  primaryLight: '#E5F1FF',
  secondary: '#5856D6',
  accent: '#FF9500',
  text: '#1C1C1E',
  textSecondary: '#3A3A3C',
  textMuted: '#8E8E93',
  border: '#E5E5EA',
  success: '#34C759',
  warning: '#FF9500',
  error: '#FF3B30',
  info: '#5AC8FA',
  operator: '#FF9500',
  operatorBg: '#FFF5E6',
  number: '#1C1C1E',
  numberBg: '#F2F2F7',
  function: '#5856D6',
  functionBg: '#F0EFFF',
  equals: '#FFFFFF',
  equalsBg: '#34C759',
  displayText: '#1C1C1E',
  historyText: '#8E8E93',
  keypadBg: '#FFFFFF',
  cardBg: '#FFFFFF',
  gradientStart: '#007AFF',
  gradientEnd: '#5856D6',
  overlay: 'rgba(0,0,0,0.4)',
  shadow: 'rgba(0,0,0,0.1)',
};

export const darkColors: ThemeColors = {
  background: '#0F0F0F',
  surface: '#1C1C1E',
  surfaceElevated: '#2C2C2E',
  primary: '#0A84FF',
  primaryLight: '#1C3A5E',
  secondary: '#5E5CE6',
  accent: '#FF9F0A',
  text: '#FFFFFF',
  textSecondary: '#EBEBF5',
  textMuted: '#8E8E93',
  border: '#38383A',
  success: '#30D158',
  warning: '#FF9F0A',
  error: '#FF453A',
  info: '#64D2FF',
  operator: '#FF9F0A',
  operatorBg: '#2A2000',
  number: '#FFFFFF',
  numberBg: '#2C2C2E',
  function: '#5E5CE6',
  functionBg: '#1C1C3E',
  equals: '#FFFFFF',
  equalsBg: '#30D158',
  displayText: '#FFFFFF',
  historyText: '#8E8E93',
  keypadBg: '#1C1C1E',
  cardBg: '#2C2C2E',
  gradientStart: '#0A84FF',
  gradientEnd: '#5E5CE6',
  overlay: 'rgba(0,0,0,0.6)',
  shadow: 'rgba(0,0,0,0.3)',
};
